loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDD/main/lua"))()

print("")
print("Prefix (.)")
print("")
print("1. kill all/others/me OR anyone's display/username")
print("2. win round OR win game")
print("3. infv OR infv auto = infinite votes (YES)")
print("4. admin on/off (BAN) risk")
print("5. serverhop")
print("")
