loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDDDDD/main/lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/TRASHUX/K1LDDDDDDDD/main/lua"))()

print("")
print("> Script: W33D")
print("> Version: 3.0")
print("> Prefix (.)")
print("")
print("> kill all/others/random/me")
print("> win round OR win game")
print("> infv OR infv auto true/false")
print("> kills/wins/shells (number)")
print("> admin true/false (BAN) risk")
print("> show names true/false")
print("> brightness true/false")
print("> earape true/false")
print("> shoot")
print("> serverhop")
print("")
